In [1]:
import pandas as pd
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [2]:
df = pd.read_csv('/content/drive/MyDrive/gradexpert2024/final_project/Hospital_data.csv')
df

,ID,Date IN,Date OUT,Branch,Name,Age,Gender,Hospital Care,Room,Doctor,Surgery,Lab,Drug Types,Drug Brands,Drug Qty,Food,Admin,COGS,Payment,Review
0,30591,2020-01-01,2020-01-03,RSMD,Ifa Namaga,65,Laki-laki,Rawat Inap,Kelas 2,Bedah,Kusus,Hematologi,Umum,Calpol,4,80000,50000,13719597,Asuransi,Netral
1,46456,2020-01-01,2020-01-05,RSMA,Rizki Mahendra,55,Laki-laki,Rawat Inap,Kelas 1,Bedah,Kusus,Serologi,Vitamin,Holland & Barrett,1,110000,50000,14625784,Pribadi,Sangat Tidak Puas
2,99188,2020-01-01,2020-01-01,RSMD,Rahmi Safitri,38,Laki-laki,Rawat Jalan,-,Bedah,-,Hematologi,Vitamin,Enervon-C,5,-,50000,3859519,Pribadi,Sangat Puas
3,23001,2020-01-01,2020-01-05,RSMA,Gandi Situmorang,37,Laki-laki,Rawat Inap,VIP,Bedah,Kecil,Rontgen,Antibiotik,Amoxicillin,2,150000,50000,6086762,Asuransi,Netral
4,29319,2020-01-01,2020-01-02,RSMS,Oliva Waluyo,36,Laki-laki,Rawat Inap,VIP,Kandungan,-,Serologi,Antibiotik,Ciprofloxacin,3,150000,50000,3003078,Asuransi,Sangat Tidak Puas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9469,17738,2023-12-31,2024-01-05,RSMS,Among Prayoga,80,Laki-laki,Rawat Inap,VIP,Kandungan,Kusus,Kimia Darah,Antibiotik,Ciprofloxacin,5,150000,50000,15241859,Pribadi,Sangat Puas
9470,53105,2023-12-31,2024-01-02,RSMA,Kajen Sihombing,20,Laki-laki,Rawat Inap,Kelas 2,Kandungan,Besar,Kimia Darah,Vitamin,Holland & Barrett,4,80000,50000,9142530,Pribadi,Sangat Tidak Puas
9471,44283,2023-12-31,2024-01-02,RSMS,Shakila Waskita,77,Perempuan,Rawat Inap,Kelas 3,Umum,Kecil,-,Pereda Nyeri,Tramadol,2,50000,50000,7627666,Pribadi,Tidak Puas
9472,67808,2023-12-31,2024-01-01,RSMD,"drg. Eka Putra, S.Ked",23,Laki-laki,Rawat Inap,Kelas 1,Gigi,-,Urinalisa,Vitamin,Blackmores,2,110000,50000,4066929,Asuransi,Sangat Puas
9473,28891,2023-12-31,2024-01-03,RSMA,R.M. Ibrani Tamba,29,Perempuan,Rawat Inap,Kelas 3,Bedah,Kusus,Serologi,Antibiotik,Ciprofloxacin,4,50000,50000,14462395,Asuransi,Puas

In [3]:
df.columns

Index(['ID', 'Date IN', 'Date OUT', 'Branch', 'Name', 'Age', 'Gender',
       'Hospital Care', 'Room', 'Doctor', 'Surgery', 'Lab', 'Drug Types',
       'Drug Brands', 'Drug Qty', 'Food', 'Admin', 'COGS', 'Payment',
       'Review'],
      dtype='object')

In [4]:
patient = df[['Name', 'Age', 'Gender']]
patient = patient.drop_duplicates()
patient['patient_id'] = range(1, len(patient) + 1)
patient['patient_id'] = patient['patient_id'].astype(int)
patient.to_csv('patient.csv', index = False)

In [5]:
room = df[['Room', 'Food']]
room = room[room['Room'] != '-']
room = room.sort_values(by = 'Room')
room = room.drop_duplicates().reset_index()

for i in range(len(room)):
    if room.loc[i,'Room'] == 'Kelas 3':
       room.loc[i,'Room Price'] = 150000
    elif room.loc[i,'Room'] == 'Kelas 2':
       room.loc[i,'Room Price'] = 200000
    elif room.loc[i,'Room'] == 'Kelas 1':
       room.loc[i,'Room Price'] = 250000
    elif room.loc[i,'Room'] == 'VIP':
       room.loc[i,'Room Price'] = 300000
    else:
       room.loc[i,'Room Price'] = '-'
room['room_id'] = range(1, len(room) + 1)
room['room_id'] = room['room_id'].astype(int)
room.drop(columns = 'index', inplace = True)
room.to_csv('room.csv', index = False)

Tipe obat:
- Antibiotik : Rp. 75.000
- Pereda nyeri : Rp. 50.000
- Umum : Rp. 40.000
- Vitamin : Rp. 110.000

In [7]:
drugs = df[['Drug Brands', 'Drug Types']]
drugs = drugs.drop_duplicates().reset_index()
for i in range(len(drugs)):
    if drugs.loc[i,'Drug Types'] == 'Antibiotik':
       drugs.loc[i,'Drug Price per Item'] = 75000
    if drugs.loc[i,'Drug Types'] == 'Pereda Nyeri':
       drugs.loc[i,'Drug Price per Item'] = 50000
    if drugs.loc[i,'Drug Types'] == 'Umum':
       drugs.loc[i,'Drug Price per Item'] = 40000
    if drugs.loc[i,'Drug Types'] == 'Vitamin':
       drugs.loc[i,'Drug Price per Item'] = 110000
drugs['drug_id'] = range(1, len(drugs) + 1)
drugs['drug_id'] = drugs['drug_id'].astype(int)
drugs.drop(columns = 'index', inplace = True)
drugs.to_csv('drugs.csv', index = False)

In [8]:
df.groupby(['Name', 'Age'])['Name'].count().reset_index(name = 'count').sort_values(by = 'count', ascending = False)

                             Name  Age  count
7378               Septi Haryanti   73      2
6941                Rahmi Narpati   70      2
0           Abyasa Damanik, S.Kom   43      1
6316                Qori Agustina   74      1
6311                 Putri Yuniar   39      1
...                           ...  ...    ...
3157              Harsana Hidayat   40      1
3158             Harsana Hutasoit   48      1
3159           Harsana Laksmiwati   28      1
3160       Harsana Nasyiah, S.Ked   69      1
9471  drg. Zulfa Iswahyudi, S.E.I   44      1

[9472 rows x 3 columns]

Tipe doktor:
- Bedah : Rp. 300.000/kunjungan
- Gigi : Rp. 300.000/kunjungan
- Kandungan : Rp. 300.000/kunjungan
- Penyakit dalam : Rp. 300.000/kunjungan
- Umum : Rp. 200.000/kunjungan

In [9]:
doctor = df['Doctor']
doctor = doctor.drop_duplicates().reset_index()
for i in range(len(doctor)):
    if doctor.loc[i,'Doctor'] == 'Bedah':
       doctor.loc[i,'Doctor Price'] = 300000
    elif doctor.loc[i,'Doctor'] == 'Gigi':
       doctor.loc[i,'Doctor Price'] = 300000
    elif doctor.loc[i,'Doctor'] == 'Kandungan':
       doctor.loc[i,'Doctor Price'] = 300000
    elif doctor.loc[i,'Doctor'] == 'Penyakit Dalam':
       doctor.loc[i,'Doctor Price'] = 300000
    elif doctor.loc[i,'Doctor'] == 'Umum':
       doctor.loc[i,'Doctor Price'] = 250000
doctor['doctor_id'] = range(1, len(doctor) + 1)
doctor['doctor_id'] = doctor['doctor_id'].astype(int)
doctor.drop(columns = 'index', inplace = True)
doctor.to_csv('doctor.csv', index = False)

Tipe tindakan/operasi:
- Kecil : Rp. 4.000.000
- Besar : Rp. 8.000.000
- Kusus : Rp. 15.000.000

In [10]:
surgery = df[['Surgery']]
surgery = surgery[surgery['Surgery'] != '-']
surgery = surgery.drop_duplicates().reset_index()
for i in range(len(surgery)):
    if surgery.loc[i,'Surgery'] == 'Kecil':
       surgery.loc[i,'Surgery Price'] = 4000000
    elif surgery.loc[i,'Surgery'] == 'Besar':
       surgery.loc[i,'Surgery Price'] = 8000000
    elif surgery.loc[i,'Surgery'] == 'Kusus':
       surgery.loc[i,'Surgery Price'] = 15000000
surgery['surgery_id'] = range(1, len(surgery) + 1)
surgery['surgery_id'] = surgery['surgery_id'].astype(int)
surgery.drop(columns = 'index', inplace = True)
surgery.to_csv('surgery.csv', index = False)

Tipe uji laboratorium:
- Hematologi : Rp. 90.000
- Kimia Darah : Rp. 195.000
- Rontgen : Rp. 150.000
- Serologi : Rp. 200.000
- Urinalisa : Rp. 80.000

In [11]:
Lab = df[['Lab']]
Lab = Lab[Lab["Lab"] != '-']
Lab = Lab.drop_duplicates().reset_index()
for i in range(len(Lab)):
    if Lab.loc[i,'Lab'] == 'Hematologi':
       Lab.loc[i,'Lab Price'] = 90000
    elif Lab.loc[i,'Lab'] == 'Kimia Darah':
       Lab.loc[i,'Lab Price'] = 195000
    elif Lab.loc[i,'Lab'] == 'Rontgen':
       Lab.loc[i,'Lab Price'] = 150000
    elif Lab.loc[i,'Lab'] == 'Serologi':
       Lab.loc[i,'Lab Price'] = 200000
    elif Lab.loc[i,'Lab'] == 'Urinalisa':
       Lab.loc[i,'Lab Price'] = 80000
Lab['lab_id'] = range(1, len(Lab) + 1)
Lab['lab_id'] = Lab['lab_id'].astype(int)
Lab.drop(columns = 'index', inplace = True)
Lab.to_csv('lab.csv', index = False)

In [12]:
df1 = df
df1 = df1.merge(patient, how = 'left', on = ['Name', 'Age', "Gender"])
df1 = df1.merge(room, how = 'left', on = 'Room')
df1 = df1.merge(drugs, how = 'left', on = 'Drug Brands')
df1 = df1.merge(doctor, how = 'left', on = 'Doctor')
df1 = df1.merge(surgery, how = 'left', on = 'Surgery')
df1 = df1.merge(Lab, how = 'left', on = 'Lab')
df1.drop(columns = ['Drug Types_x', 'Food_x', 'Food_y', 'Room Price','Drug Types_y', 'Drug Price per Item', 'Doctor Price', 'Surgery Price', 'Lab Price'], inplace = True)
df1.columns

df1.to_csv('hospital.csv', index = False)